import { CandidateRecord, JobDescriptionResult } from "./types";

export const MOCK_JOB_DESCRIPTION: JobDescriptionResult = {
  job_title: "Data Analyst",
  raw_text: "",
  required_skills: ["python", "sql", "pandas", "docker", "aws"],
  essential_skills: ["python", "sql"],
  desirable_skills: ["docker", "aws"],
};

export const MOCK_CANDIDATES: CandidateRecord[] = [
  {
    candidate_id: "cand_001",
    name: "D. Johnson",
    source_file: "D_Johnson_CV.pdf",
    extraction_status: "ok",
    raw_text_chars: 5210,
    skills_found: ["python", "sql", "pandas", "docker", "aws"],
    skills_matched: ["python", "sql", "pandas", "docker", "aws"],
    skills_missing: [],
    similarity_raw: 0.91,
    match_score: 99,
    rank: 1,
    summary:
      "Full stack data engineer with all required skills and production experience across the entire pipeline.",
    warnings: [],
  },
  {
    candidate_id: "cand_002",
    name: "A. Rahman",
    source_file: "resume_001.pdf",
    extraction_status: "ok",
    raw_text_chars: 4821,
    skills_found: ["python", "pandas", "sql"],
    skills_matched: ["python", "pandas", "sql"],
    skills_missing: ["docker", "aws"],
    similarity_raw: 0.84,
    match_score: 92,
    rank: 2,
    summary:
      "Senior data analyst with 5 years of experience in data modeling, ETL, and reporting.",
    warnings: [],
  },
  {
    candidate_id: "cand_003",
    name: "J. Smith",
    source_file: "J_Smith_Resume_Final.pdf",
    extraction_status: "ok",
    raw_text_chars: 3980,
    skills_found: ["python", "docker", "aws", "sql", "pandas"],
    skills_matched: ["python", "docker", "aws"],
    skills_missing: ["sql", "pandas"],
    similarity_raw: 0.77,
    match_score: 85,
    rank: 3,
    summary:
      "Backend engineer transitioning into data analysis, strong infrastructure background.",
    warnings: ["Low text density on page 2"],
  },
  {
    candidate_id: "cand_004",
    name: "M. Garcia",
    source_file: "MG_Data_Analyst.pdf",
    extraction_status: "ok",
    raw_text_chars: 4102,
    skills_found: ["python", "sql"],
    skills_matched: ["python", "sql"],
    skills_missing: ["pandas", "docker", "aws"],
    similarity_raw: 0.61,
    match_score: 73,
    rank: 4,
    summary:
      "Business analyst with deep SQL and BI tool expertise, recently started using Python.",
    warnings: [],
  },
  {
    candidate_id: "cand_005",
    name: "K. Williams",
    source_file: "Williams_K.pdf",
    extraction_status: "ok",
    raw_text_chars: 2890,
    skills_found: ["sql", "pandas"],
    skills_matched: ["sql", "pandas"],
    skills_missing: ["python", "docker", "aws"],
    similarity_raw: 0.48,
    match_score: 65,
    rank: 5,
    summary:
      "Data analyst with good data manipulation skills but missing infrastructure knowledge.",
    warnings: [],
  },
  {
    candidate_id: "cand_006",
    name: "R. Patel",
    source_file: "RPatel.pdf",
    extraction_status: "ok",
    raw_text_chars: 1560,
    skills_found: [],
    skills_matched: [],
    skills_missing: ["python", "sql", "pandas", "docker", "aws"],
    similarity_raw: 0.09,
    match_score: 15,
    rank: 6,
    summary:
      "Administrative assistant with no clearly evidenced technical skills for this role.",
    warnings: ["Very short resume, limited signal"],
  },
  {
    candidate_id: "cand_007",
    name: "scan_00412",
    source_file: "scan_00412.pdf",
    extraction_status: "empty_text",
    raw_text_chars: 0,
    skills_found: [],
    skills_matched: [],
    skills_missing: ["python", "sql", "pandas", "docker", "aws"],
    similarity_raw: 0,
    match_score: 0,
    rank: 7,
    summary: "",
    warnings: ["Scanned or image only PDF, no extractable text"],
  },
  {
    candidate_id: "cand_008",
    name: "SLee_Resume",
    source_file: "SLee_Resume.pdf",
    extraction_status: "parse_error",
    raw_text_chars: 0,
    skills_found: [],
    skills_matched: [],
    skills_missing: ["python", "sql", "pandas", "docker", "aws"],
    similarity_raw: 0,
    match_score: 0,
    rank: 8,
    summary: "",
    warnings: ["File could not be parsed"],
  },
];